### ISSUE TITLE
Timeline not zooming on selection

### ISSUE THREAD

**Issue by Guillaume-Developer** [sinequa/sba-angular#37]
I noticed a new issue of the timeline not zooming to the selected time area, which was introduced after the change made in the commit `f3c7fabf`. 
I checked without the changes made in this commit and the problem disappeared.
I also noticed that this same issue appears (before and after this commit) when we're zooming on the timeline and then selecting a time area.

Find below a screenshot of the issue.

![image](https://user-images.githubusercontent.com/65693851/127419165-426e8fed-3b2e-4f3f-a8e1-92791aab63f6.png)

**Comment by ericleib** [comment]
Actually, this is on purpose. The previous behavior (automatically zooming upon selection) was a side-effect of:
- the user not manually zooming in and out (resulting in the x-scale being recomputed every time the data changes)
- the input aggregation being modified by the time selection

This was reported as a bug because sometimes the new scale was smaller than the selection.

It would be possible to develop a proper zoom-on-selection feature (for example, fixing the scale to the selection with 10% margin before and after).

**Comment by Guillaume-Developer** [comment]
Alright I see. Is this something that you're planning on developping or is it something that I'll need to develop myself if I need it?

**Comment by ericleib** [comment]
It's not planned at the moment. The way to implement it is simple, but it could have side effects.

in FacetTimeline, at the beginning of `ngOnChanges()`, you can modify the code like this:

       
        // Forget about the previous scale when there is new data
        this.currentRange = undefined;

        // Retrieve the current active selection for this timeline (if any)
        const select = this.searchService.query.findSelect(this.name);

        // Update the selection if it is not already set (which is the case on a page refresh)
        if(select) {

Notice I removed the `& !this.selection` to force the execution of the code in the if (if you notice, there is a piece of code that "guesses" a good range based on the selection).
